PayrollCompany/Models/Payroll.cs
using System.ComponentModel.DataAnnotations;

namespace PayrollCompany.Models
{
    public class Payroll
    {
        public int PayrollID { get; set; }

        [Required(ErrorMessage = "Please select an employee")]
        public int EmployeeID { get; set; } //foreign key
        public Employee Employee { get; set; }

        [Required(ErrorMessage = "Please enter the severance of the employee")]
        public double serverance { get; set; }

        [Required(ErrorMessage = "Please enter the net pay of the employee")]
        public double NetPay { get; set; }

        [Required(ErrorMessage = "Please enter the gross pay of the employee")]
        public double GrossPay { get; set; }

        [Required(ErrorMessage = "Please enter the tax percent withdrawal of the employee")]
        public double TaxPercentWidthdrawal { get; set; }

    }
}

PayrollCompany/Areas/Admin/Controllers/PayrollController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PayrollCompany.Models;
using System.Collections.Generic;
using System.Linq;

namespace PayrollCompany.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PayrollController : Controller
    {
        private PayrollContext context;
        private List<Employee> employees;

        public PayrollController(PayrollContext ctx)
        {
            context = ctx;
            employees = context.Employee.OrderBy(e => e.EmployeeID).ToList();
        }
        public IActionResult Index()
        {
            return RedirectToAction("List");
        }

        [Route("[area]/Payroll/{id?}")]
        public IActionResult List(string id = "All")
        {
            List<Payroll> payroll;
            if (id == "All")
            {
                payroll = context.Payroll.OrderBy(p => p.PayrollID).ToList();
            }
            else
            {
                payroll = context.Payroll.Where(p => p.Employee.LastName == id).OrderBy(b => b.PayrollID).ToList();
            }
            ViewBag.Employee = employees;
            ViewBag.SelectedEmployeeName = id;

            return View(payroll);
        }

        [HttpGet]
        public IActionResult Add()
        {
            Payroll payroll = new Payroll();
            payroll.Employee = context.Employee.Find(1);

            ViewBag.Action = "Add";
            ViewBag.Employee = employees;
            return View("AddUpdate", payroll);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            Payroll payroll = context.Payroll.Include(e => e.Employee).FirstOrDefault(e => e.PayrollID == id);

            ViewBag.Action = "Update";
            ViewBag.Employee = employees;

            return View("AddUpdate", payroll);
        }
        [HttpPost]
        public IActionResult Update(Payroll payroll)
        {
            if (ModelState.IsValid)
            {
                if (payroll.PayrollID == 0)
                {
                    context.Payroll.Add(payroll);
                }
                else
                {
                    context.Payroll.Update(payroll);
                }
                context.SaveChanges();
                return RedirectToAction("List");
            }
            else
            {
                ViewBag.Action = "Update";
                ViewBag.Employee = employees;
                return View("AddUpdate", payroll);
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Payroll payroll = context.Payroll.Find(id);
            return View(payroll);
        }
        [HttpPost]
        public IActionResult Delete (Payroll payroll)
        {
            context.Payroll.Remove(payroll);
            context.SaveChanges();
            return RedirectToAction("List");
        }

    }
}

PayrollCompany/Areas/Admin/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Mvc;
using PayrollCompany.Models;
using System.Collections.Generic;
using System.Linq;

namespace PayrollCompany.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProjectController : Controller
    {
        private PayrollContext context;

        public ProjectController(PayrollContext ctx)
        {
            context = ctx;

        }
        public IActionResult Index()
        {
            return RedirectToAction("List");
        }

        [Route("[area]/Project/{id?}")]
        public IActionResult List()
        {
            var projects = context.Project
                .OrderBy(c => c.ProjectID).ToList();
            return View(projects);
        }
        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Action = "Add";
            return View("AddUpdate", new Project());
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            ViewBag.Action = "Update";
            Project project = context.Project.Find(id);
            return View("AddUpdate", project);
        }

        [HttpPost]
        public IActionResult Update(Project project)
        {
            if (ModelState.IsValid)
            {
                if (project.ProjectID == 0)
                {
                    context.Project.Add(project);
                }
                else
                {
                    context.Project.Update(project);
                }
                context.SaveChanges();
                return RedirectToAction("List");
            }
            else
            {
                ViewBag.Action = "Save";
                return View("AddUpdate");
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Project project = context.Project.Find(id);
            return View(project);
        }


        [HttpPost]
        public IActionResult Delete(Project project)
        {
            context.Project.Remove(project);
            context.SaveChanges();
            return RedirectToAction("List");
        }
    }
}

PayrollCompany/Areas/Admin/Views/Payroll/AddUpdate.cshtml
@model Payroll
@{
    string title = ViewBag.Action + " Payroll";
    ViewBag.Title = title;   
}

<h1>@ViewBag.Title</h1>

<form asp-action="Update" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="EmployeeID">Employee First Name: </label>
        <select asp-for="EmployeeID"
                asp-items="@(new SelectList(ViewBag.Employee,
                         "EmployeeID", "FirstName",
                         Model.EmployeeID.ToString()))"
                class="form-control"></select>
    </div>
    <div class="form-group">
        <label asp-for="EmployeeID">Employee Last Name: </label>
        <select asp-for="EmployeeID"
                asp-items="@(new SelectList(ViewBag.Employee,
                         "EmployeeID", "LastName",
                         Model.EmployeeID.ToString()))"
                class="form-control"></select>
    </div>

    <div class="form-group">
        <label asp-for="serverance">Severance: </label>
        <input asp-for="serverance" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="NetPay">Net Pay: </label>
        <input asp-for="NetPay" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="GrossPay">Gross Pay: </label>
        <input asp-for="GrossPay" class="form-control">
    </div>
    <div class="form-group">
         <label asp-for="TaxPercentWidthdrawal">Amount Taken from Taxes: </label>
         <input asp-for="TaxPercentWidthdrawal" class="form-control">
     </div>

    <input type="hidden" asp-for="PayrollID" />

    <button type="submit" class="btn btn-primary">@ViewBag.Action</button>
    <a asp-action="List" class="btn btn-secondary">Cancel</a>
</form>

PayrollCompany/Areas/Admin/Views/Payroll/Delete.cshtml
@model Payroll
@{
    ViewBag.Title = "Delete Payroll";
}

<h1>Confirm Deletion</h1>
<h3>@Model.PayrollID</h3>

<form asp-action="Delete" method="post">
    <input type="hidden" asp-for="PayrollID" />

    <button type="submit" class="btn btn-primary">Delete</button>
    <a asp-action="List" class="btn btn-secondary">Cancel</a>
</form>


PayrollCompany/Areas/Admin/Views/Payroll/List.cshtml
@model List<Payroll>
@{
    ViewBag.Title = "Payroll Manager";
}

<h1>@ViewBag.Title</h1>
<div class="row">
    <div class="col-sm-2">
        <ul class="list-group">
            <a asp-action="List" asp-route-id="All"
               class="list-group-item
                @if (ViewBag.SelectedEmployeeName == "All") {
                    <text>active</text>
                } ">All</a>
            @foreach (Employee c in ViewBag.Employee)
            {
                <a asp-action="List" asp-route-id="@c.LastName"
                   class="list-group-item
                         @(ViewBag.SelectedEmployeeName == c.LastName ? "active" : "")">
                    @c.LastName
                </a>
            }
        </ul>
    </div>
    <div class="col-sm-10">
        <div class="col-sm-2">
            </br>
            <p1></p1>
        </div> <a asp-controller="Payroll" asp-action="Add" class="btn btn-primary bg-transparent text-primary">Add New Payroll</a>
        </br>
        <p2></p2>
        </br>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Employee ID</th>
                    <th>Severance</th>
                    <th>Net Pay</th>
                    <th>Gross Pay</th>
                    <th>Tax Percent Withdrawal</th>
                    <th></th>
            </thead>
            <tbody>
                @foreach (var p in Model)
                {
                    <tr>
                        <td>@p.EmployeeID</td>
                        <td>@p.serverance.ToString("C")</td>
                        <td>@p.NetPay.ToString("C")</td>
                        <td>@p.GrossPay.ToString("C")</td>
                        <td>@p.TaxPercentWidthdrawal.ToString("C")</td>
                        <td>
                            <a class="btn btn-primary"  asp-action="Update"
                               asp-route-id="@p.PayrollID">Update</a>
                        </td>
                        <td>
                            <a class ="btn btn-danger" asp-action="Delete"
                               asp-route-id="@p.PayrollID">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

PayrollCompany/Areas/Admin/Views/Payroll/Payroll.cshtml
@{
    ViewBag.Title = "Payroll";
}

<br /><br />
<div class="row">
    <div class="col-sm-4">
        <div class="list-group">
            <a asp-controller="Project" asp-action="Delete"
               class="list-group-item">Delete</a>
            <a asp-controller="Project" asp-action="Add"
               class="list-group-item">Add</a>
            <a asp-controller="Project" asp-action="Update"
               class="list-group-item">Update</a>
            <a asp-controller="Project" asp-action="List"
               class="list-group-item">"Payroll Manager"</a>
        </div>
    </div>
</div>