PayrollCompany/Models/EmployeeProject.cs
using System.ComponentModel.DataAnnotations;

namespace PayrollCompany.Models
{
    public class EmployeeProject
    {
        public int EmployeeProjectID { get; set; }

        [Required(ErrorMessage = "Please enter the project ID")]
        public int EmployeeID { get; set; }

        [Required(ErrorMessage = "Please enter the employee ID")]
        public int ProjectID { get; set; }

        public Employee Employee { get; set; }
        public Project Project { get; set; }
    }
}

PayrollCompany/Areas/Admin/Controllers/EmployeeProjectController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PayrollCompany.Models;
using System.Collections.Generic;
using System.Linq;

namespace PayrollCompany.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class EmployeeProjectController : Controller
    {
        private PayrollContext context;
        private List<Employee> employees;
        private List<Project> projects;

        public EmployeeProjectController(PayrollContext ctx)
        {
            context = ctx;
            employees = context.Employee.OrderBy(c => c.EmployeeID).ToList();
            projects = context.Project.OrderBy(c => c.ProjectID).ToList();
        }
        public IActionResult Index()
        {
            return View("List");
        }

        [Route("[area]/EmployeeProject/{id?}")]
        public IActionResult List(string id = "All")
        {
            List<EmployeeProject> employeeProjects;
            if (id == "All")
            {
                employeeProjects = context.EmployeeProject.OrderBy(p => p.EmployeeProjectID).ToList();
            }
            else
            {
                employeeProjects = context.EmployeeProject.Where(p => p.Project.ProjectName == id).OrderBy(p=>p.EmployeeProjectID).ToList();
            }

            ViewBag.Project = projects;
            ViewBag.SelectedProjectName = id;
            return View(employeeProjects);

        }

        [HttpGet]
        public IActionResult Assign()
        {
            EmployeeProject employeeProject = new EmployeeProject();
            //employeeProject.Employee = context.Employee.Find(1);
            //employeeProject.Project = context.Project.Find(1);

            ViewBag.Employee = employees;
            ViewBag.Project = projects;
            ViewBag.Action = "Assign";
            return View("Assign", new EmployeeProject());

        }
        [HttpPost]
        public IActionResult Assign(EmployeeProject employeeProject)
        {
            if (ModelState.IsValid)
            {
                if (employeeProject.EmployeeProjectID == 0)
                {
                    context.EmployeeProject.Add(employeeProject);
                }
                context.SaveChanges();
                return RedirectToAction("List");
            }
            else
            {
                ViewBag.Employee = employees;
                ViewBag.Project = projects;
                ViewBag.Action = "Assign";
                return View("Assign", employeeProject);
            }
        }

        [HttpGet]
        public IActionResult Deassign(int id)
        {
            EmployeeProject employeeProject = context.EmployeeProject.Find(id);
            return View(employeeProject);
        }

        [HttpPost]
        public IActionResult Deassign(EmployeeProject employeeProject)
        {
            context.EmployeeProject.Remove(employeeProject);
            context.SaveChanges();
            return RedirectToAction("List");
        }
    }
}

PayrollCompany/Areas/Admin/Views/EmployeeProject/Assign.cshtml
@model EmployeeProject
@{
    ViewBag.Title = "Assign Project";
}
<h1>@ViewBag.Title</h1>

<form asp-action="Assign" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Project.ProjectName"> Project Name: </label>
        <input asp-for="Project.ProjectName" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Project.ProjectTimespan"> Project Time Span: </label>
        <input asp-for="Project.ProjectTimespan" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Employee.FirstName"> Employee First Name: </label>
        <input asp-for="Employee.FirstName" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Employee.LastName"> Employee Last Name: </label>
        <input asp-for="Employee.LastName" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Employee.Title"> Employee Title: </label>
        <input asp-for="Employee.Title" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Employee.Username"> Employee Username: </label>
        <input asp-for="Employee.Username" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Employee.Password"> Employee Password: </label>
        <input asp-for="Employee.Password" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Employee.Address">Employee's Address: </label>
        <input asp-for="Employee.Address" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Employee.City">Employee's City: </label>
        <input asp-for="Employee.City" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Employee.State">Employee's State: </label>
        <input asp-for="Employee.State" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Employee.ZipCode">Employee's Zip Code: </label>
        <input asp-for="Employee.ZipCode" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Employee.DepartmentID">Department: </label>
        <input asp-for="Employee.DepartmentID" class="form-control" />
        </div>

    <input type="hidden" asp-for="EmployeeProjectID" />

    <button type="submit" class="btn btn-primary">@ViewBag.Action</button>
    <a asp-action="List" class="btn btn-secondary">Cancel</a>
</form>

PayrollCompany/Areas/Admin/Views/EmployeeProject/Deassign.cshtml
@model EmployeeProject
@{
    ViewBag.Title = "Deassign Project";
}
<h1>Confirm Deassignment</h1>


<form asp-action="Deassign" method="post">
     <input type="hidden" asp-for="EmployeeProjectID" />

    <button type="submit" class="btn btn-danger">Delete</button>
    <a asp-action="List" class="btn btn-secondary">Cancel</a>
</form>

PayrollCompany/Areas/Admin/Views/EmployeeProject/EmployeeProject.cshtml
@model EmployeeProject
@{
    ViewBag.Title = "Employee";
}

<br /><br />
<div class="row">
    <div class="col-sm-4">
        <div class="list-group">
            <a asp-controller="EmployeeProject" asp-action="Assign"
               class="list-group-item">Assign Project</a>
            <a asp-controller="EmployeeProject" asp-action="Deassign"
               class="list-group-item">Deassign Project</a>
             <a asp-controller="EmployeeProject" asp-action="List"
               class="list-group-item">Employee & Project Manager</a>
        </div>
    </div>
</div>

PayrollCompany/Areas/Admin/Views/EmployeeProject/List.cshtml
@model List<EmployeeProject>
@{
    ViewBag.Title = "Product Manager";
}
<h1>@ViewBag.Title</h1>
<div class="row">
    <div class="col-sm-2">
        <ul class="list-group">
            <a asp-action="List" asp-route-id="All"
               class="list-group-item
               @if (ViewBag.SelectedProjectName == "All") {
                    <text>active</text>
                } ">All</a>
            @foreach (Project c in ViewBag.Project)
            {
                <a asp-action="List" asp-route-id="@c.ProjectName"
               class="list-group-item
                         @(ViewBag.SelectedProjectName == c.ProjectName ? "active" : "")">
                    @c.ProjectName
                </a>
            }
        </ul>
    </div>
<div class="col-sm-10">
    </br>
    <p1></p1>
    <a asp-action="Assign" class="btn btn-primary bg-transparent text-primary">Assign New Project</a>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Project Name</th>
                <th>Employee Name</th>
                <th></th>

        </thead>
        <tbody>
            @foreach (var p in Model)
            {
                        <tr>
                            <td>@p.Project.ProjectName </td>
                            <td>@p.Employee.FirstName @p.Employee.LastName </td>
                            <td>
                                <a class="btn btn-danger" asp-action="Deassign"
                                  asp-route-id="@p.EmployeeProjectID">Deassign</a>
                            </td>
                        </tr>


            }
        </tbody>
    </table>
</div>
</div>


